<a href="https://colab.research.google.com/github/QuantamDev/Matplotlib/blob/main/Job_anlaysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [26]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [28]:
df=pd.read_csv("/content/drive/MyDrive/Dataset/jobs_in_data.csv")

In [29]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9355 entries, 0 to 9354
Data columns (total 12 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   work_year           9355 non-null   int64
 1   job_title           9355 non-null   object
 2   job_category        9355 non-null   object
 3   salary_currency     9355 non-null   object
 4   salary              9355 non-null   int64
 5   salary_in_usd       9355 non-null   int64
 6   employee_residence  9355 non-null   object
 7   experience_level    9355 non-null   object
 8   employment_type     9355 non-null   object
 9   work_setting        9355 non-null   object
 10  company_location    9355 non-null   object
 11  company_size        9355 non-null   object
dtypes: int64(3), object(9)
memory usage: 877.2+ KB

In [30]:
df.info

<bound method DataFrame.info of       work_year                 job_title                    job_category  \
0          2023      Data DevOps Engineer                Data Engineering
1          2023            Data Architect  Data Architecture and Modeling
2          2023            Data Architect  Data Architecture and Modeling
3          2023            Data Scientist       Data Science and Research
4          2023            Data Scientist       Data Science and Research
...         ...                       ...                             ...
9350       2021           Data Specialist    Data Management and Strategy
9351       2020            Data Scientist       Data Science and Research
9352       2021  Principal Data Scientist       Data Science and Research
9353       2020            Data Scientist       Data Science and Research
9354       2020     Business Data Analyst                   Data Analysis

     salary_currency  salary  salary_in_usd employee_residence  \
0                EUR   88000          95012            Germany
1                USD  186000         186000      United States
2                USD   81800          81800      United States
3                USD  212000         212000      United States
4                USD   93300          93300      United States
...              ...     ...            ...                ...
9350             USD  165000         165000      United States
9351             USD  412000         412000      United States
9352             USD  151000         151000      United States
9353             USD  105000         105000      United States
9354             USD  100000         100000      United States

     experience_level employment_type work_setting company_location  \
0           Mid-level       Full-time       Hybrid          Germany
1              Senior       Full-time    In-person    United States
2              Senior       Full-time    In-person    United States
3              Senior       Full-time    In-person    United States
4              Senior       Full-time    In-person    United States
...               ...             ...          ...              ...
9350           Senior       Full-time       Remote    United States
9351           Senior       Full-time       Remote    United States
9352        Mid-level       Full-time       Remote    United States
9353      Entry-level       Full-time       Remote    United States
9354      Entry-level        Contract       Remote    United States

     company_size
0               L
1               M
2               M
3               M
4               M
...           ...
9350            L
9351            L
9352            L
9353            S
9354            L

[9355 rows x 12 columns]>

In [31]:
df.head()

,work_year,job_title,job_category,salary_currency,salary,salary_in_usd,employee_residence,experience_level,employment_type,work_setting,company_location,company_size
0,2023,Data DevOps Engineer,Data Engineering,EUR,88000,95012,Germany,Mid-level,Full-time,Hybrid,Germany,L
1,2023,Data Architect,Data Architecture and Modeling,USD,186000,186000,United States,Senior,Full-time,In-person,United States,M
2,2023,Data Architect,Data Architecture and Modeling,USD,81800,81800,United States,Senior,Full-time,In-person,United States,M
3,2023,Data Scientist,Data Science and Research,USD,212000,212000,United States,Senior,Full-time,In-person,United States,M
4,2023,Data Scientist,Data Science and Research,USD,93300,93300,United States,Senior,Full-time,In-person,United States,M

In [33]:
df.columns

Index(['work_year', 'job_title', 'job_category', 'salary_currency', 'salary',
       'salary_in_usd', 'employee_residence', 'experience_level',
       'employment_type', 'work_setting', 'company_location', 'company_size'],
      dtype='object')

In [35]:
df.shape

(9355, 12)

In [36]:
df.describe()

         work_year         salary  salary_in_usd
count  9355.000000    9355.000000    9355.000000
mean   2022.760449  149927.981293  150299.495564
std       0.519470   63608.835387   63177.372024
min    2020.000000   14000.000000   15000.000000
25%    2023.000000  105200.000000  105700.000000
50%    2023.000000  143860.000000  143000.000000
75%    2023.000000  187000.000000  186723.000000
max    2023.000000  450000.000000  450000.000000

In [40]:
df.notnull()

,work_year,job_title,job_category,salary_currency,salary,salary_in_usd,employee_residence,experience_level,employment_type,work_setting,company_location,company_size
0,True,True,True,True,True,True,True,True,True,True,True,True
1,True,True,True,True,True,True,True,True,True,True,True,True
2,True,True,True,True,True,True,True,True,True,True,True,True
3,True,True,True,True,True,True,True,True,True,True,True,True
4,True,True,True,True,True,True,True,True,True,True,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...
9350,True,True,True,True,True,True,True,True,True,True,True,True
9351,True,True,True,True,True,True,True,True,True,True,True,True
9352,True,True,True,True,True,True,True,True,True,True,True,True
9353,True,True,True,True,True,True,True,True,True,True,True,True
9354,True,True,True,True,True,True,True,True,True,True,True,True

In [41]:
df.isna().sum().sort_values(ascending=False)

work_year             0
job_title             0
job_category          0
salary_currency       0
salary                0
salary_in_usd         0
employee_residence    0
experience_level      0
employment_type       0
work_setting          0
company_location      0
company_size          0
dtype: int64

In [42]:
df

,work_year,job_title,job_category,salary_currency,salary,salary_in_usd,employee_residence,experience_level,employment_type,work_setting,company_location,company_size
0,2023,Data DevOps Engineer,Data Engineering,EUR,88000,95012,Germany,Mid-level,Full-time,Hybrid,Germany,L
1,2023,Data Architect,Data Architecture and Modeling,USD,186000,186000,United States,Senior,Full-time,In-person,United States,M
2,2023,Data Architect,Data Architecture and Modeling,USD,81800,81800,United States,Senior,Full-time,In-person,United States,M
3,2023,Data Scientist,Data Science and Research,USD,212000,212000,United States,Senior,Full-time,In-person,United States,M
4,2023,Data Scientist,Data Science and Research,USD,93300,93300,United States,Senior,Full-time,In-person,United States,M
...,...,...,...,...,...,...,...,...,...,...,...,...
9350,2021,Data Specialist,Data Management and Strategy,USD,165000,165000,United States,Senior,Full-time,Remote,United States,L
9351,2020,Data Scientist,Data Science and Research,USD,412000,412000,United States,Senior,Full-time,Remote,United States,L
9352,2021,Principal Data Scientist,Data Science and Research,USD,151000,151000,United States,Mid-level,Full-time,Remote,United States,L
9353,2020,Data Scientist,Data Science and Research,USD,105000,105000,United States,Entry-level,Full-time,Remote,United States,S
9354,2020,Business Data Analyst,Data Analysis,USD,100000,100000,United States,Entry-level,Contract,Remote,United States,L